"""Pytest runner wrapper for mutation tests and ad-hoc adversarial cases.

Two responsibilities:

1. `run_tests_for_mutant(mutant, test_ids, timeout)` — apply a mutant, run
   the impacted tests via `pytest --no-header -q`, parse the result into
   {status, killing_tests, wall_clock_seconds}, roll back.
2. `run_adversarial_case(case)` — execute an ephemeral test that asserts
   `case.expected_behavior` against the SUT for `case.input_repr`, classify
   verdict into caught_by_existing_test | uncaught | inconclusive.

CLI:

    python run.py --mutant mutant.json --tests t1 t2 --timeout 30
    python run.py --case case.json
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
import textwrap
import time
from pathlib import Path
from typing import Optional

from inject import MutationInjector


_PYTEST = [sys.executable, "-m", "pytest", "--no-header", "-q", "--tb=line"]


_FAIL_RE = re.compile(r"^FAILED\s+(\S+)", re.MULTILINE)
_PASS_RE = re.compile(r"^PASSED\s+(\S+)", re.MULTILINE)


def _guess_project_root(file_path: str) -> str:
    """Walk up from a source file to find the project root (a dir with tests/ or pyproject.toml)."""
    p = Path(file_path).resolve()
    for cur in [p.parent] + list(p.parents):
        if (cur / "tests").is_dir() or (cur / "pyproject.toml").is_file() or (cur / "setup.py").is_file():
            return str(cur)
    return str(p.parent)


def _relativize_test_ids(test_ids: list[str], cwd: str) -> list[str]:
    """Convert absolute test_ids ('/abs/tests/x.py::t_y') to cwd-relative form so pytest finds them."""
    cwd_p = Path(cwd).resolve()
    out: list[str] = []
    for tid in test_ids:
        path_part, _, name_part = tid.partition("::")
        p = Path(path_part)
        if p.is_absolute():
            try:
                rel = p.resolve().relative_to(cwd_p)
                out.append(f"{rel}::{name_part}" if name_part else str(rel))
            except ValueError:
                out.append(tid)
        else:
            out.append(tid)
    return out


def run_tests_for_mutant(mutant: dict, test_ids: list[str], timeout: int = 30, cwd: Optional[str] = None) -> dict:
    """Run a subset of tests with the mutant applied. Roll back on exit."""
    if cwd is None:
        cwd = _guess_project_root(mutant["file"])
    test_ids = _relativize_test_ids(test_ids, cwd) if test_ids else []
    cmd = _PYTEST + ["-v"] + list(test_ids)
    started = time.monotonic()
    try:
        with MutationInjector(mutant):
            try:
                proc = subprocess.run(
                    cmd, capture_output=True, text=True, timeout=timeout, check=False,
                    cwd=cwd,
                )
            except subprocess.TimeoutExpired:
                return {
                    "mutant_id": mutant["id"],
                    "status": "timeout",
                    "killing_tests": [],
                    "wall_clock_seconds": timeout,
                    "cache_status": "miss",
                }
    except Exception as e:
        return {
            "mutant_id": mutant["id"],
            "status": "error",
            "killing_tests": [],
            "wall_clock_seconds": round(time.monotonic() - started, 2),
            "error": str(e),
            "cache_status": "miss",
        }

    elapsed = round(time.monotonic() - started, 2)
    output = proc.stdout + "\n" + proc.stderr
    failed = _FAIL_RE.findall(output)

    if proc.returncode == 0:
        return {
            "mutant_id": mutant["id"], "status": "survived",
            "killing_tests": [], "wall_clock_seconds": elapsed, "cache_status": "miss",
        }
    if failed:
        return {
            "mutant_id": mutant["id"], "status": "killed",
            "killing_tests": failed, "wall_clock_seconds": elapsed, "cache_status": "miss",
        }
    return {
        "mutant_id": mutant["id"], "status": "error",
        "killing_tests": [],
        "wall_clock_seconds": elapsed,
        "detail": output[-400:],
        "cache_status": "miss",
    }


_AD_HOC_TEMPLATE = textwrap.dedent("""
    # Auto-generated by adversarial runner.
    # case_id: {case_id}
    import sys, importlib.util

    spec = importlib.util.spec_from_file_location({module_name!r}, {source_path!r})
    mod = importlib.util.module_from_spec(spec)
    sys.modules[{module_name!r}] = mod
    spec.loader.exec_module(mod)

    fn = mod
    for part in {symbol!r}.split('.'):
        fn = getattr(fn, part)

    def test_adversarial_case():
        observed = {invocation}
        expected_repr = {expected!r}
        assert repr(observed) == expected_repr or expected_repr == 'ANY', (
            f"adversarial mismatch: observed={{observed!r}} expected={{expected_repr}}"
        )
""")


def run_adversarial_case(case: dict) -> dict:
    """Render an ad-hoc test, run it, classify verdict.

    The case must include:
      target_symbol: "<source-path>:<symbol>" — source-path is the actual file path
                     (absolute or relative); symbol is dotted from module level
      invocation:    a Python expression that calls `fn(...)` with the input
      expected:      a repr() string of the expected value, or 'ANY' for soft check
    """
    sym = case["target_symbol"]
    if ":" in sym:
        source_path, symbol = sym.split(":", 1)
    else:
        source_path, symbol = sym, ""

    source_abs = str(Path(source_path).resolve())
    module_name = Path(source_path).stem + "_adv"

    rendered = _AD_HOC_TEMPLATE.format(
        case_id=case["case_id"],
        module_name=module_name,
        source_path=source_abs,
        symbol=symbol,
        invocation=case.get("invocation", "fn()"),
        expected=case.get("expected", "ANY"),
    )

    with tempfile.NamedTemporaryFile("w", prefix="adv_", suffix=".py", delete=False) as f:
        f.write(rendered)
        ad_hoc_path = Path(f.name)

    try:
        started = time.monotonic()
        proc = subprocess.run(
            _PYTEST + ["-v", str(ad_hoc_path)],
            capture_output=True, text=True, timeout=case.get("timeout", 20), check=False,
        )
        elapsed = round(time.monotonic() - started, 2)
        passed = (proc.returncode == 0)
        # caught_by_existing_test is impossible here (this case is novel by
        # construction). The verdict is uncaught if the SUT failed our
        # expected check, caught_by_existing_test if the SUT matched, and
        # inconclusive if pytest errored before evaluation.
        if passed:
            verdict = "caught_by_existing_test"
        elif "AssertionError" in proc.stdout + proc.stderr:
            verdict = "uncaught"
        else:
            verdict = "inconclusive"
        return {
            "case_id": case["case_id"],
            "verdict": verdict,
            "observed_behavior": (proc.stdout + proc.stderr)[-400:],
            "wall_clock_seconds": elapsed,
        }
    finally:
        try:
            ad_hoc_path.unlink()
        except OSError:
            pass


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--mutant", help="mutant JSON path")
    g.add_argument("--case", help="adversarial case JSON path")
    ap.add_argument("--tests", nargs="*", default=[])
    ap.add_argument("--timeout", type=int, default=30)
    ap.add_argument("--cwd", default=None, help="project root for pytest; auto-detected if omitted")
    args = ap.parse_args()

    if args.mutant:
        m = json.loads(Path(args.mutant).read_text())
        print(json.dumps(run_tests_for_mutant(m, args.tests, args.timeout, args.cwd), indent=2))
    else:
        c = json.loads(Path(args.case).read_text())
        print(json.dumps(run_adversarial_case(c), indent=2))


if __name__ == "__main__":
    main()
