"""Pytest runner wrapper for mutation tests and ad-hoc adversarial cases.

Two responsibilities:

1. `run_tests_for_mutant(mutant, test_ids, timeout)` — apply a mutant, run
   the impacted tests via `pytest --no-header -q`, parse the result into
   {status, killing_tests, wall_clock_seconds}, roll back.
2. `run_adversarial_case(case)` — execute an ephemeral test that asserts
   `case.expected_behavior` against the SUT for `case.input_repr`, classify
   verdict into caught_by_existing_test | uncaught | inconclusive.

CLI:

    python run.py --mutant mutant.json --tests t1 t2 --timeout 30
    python run.py --case case.json
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
import textwrap
import time
from pathlib import Path

from inject import MutationInjector


_PYTEST = [sys.executable, "-m", "pytest", "--no-header", "-q", "--tb=line"]


_FAIL_RE = re.compile(r"^FAILED\s+(\S+)", re.MULTILINE)
_PASS_RE = re.compile(r"^PASSED\s+(\S+)", re.MULTILINE)


def run_tests_for_mutant(mutant: dict, test_ids: list[str], timeout: int = 30) -> dict:
    """Run a subset of tests with the mutant applied. Roll back on exit."""
    cmd = _PYTEST + ["-v"] + list(test_ids)
    started = time.monotonic()
    try:
        with MutationInjector(mutant):
            try:
                proc = subprocess.run(
                    cmd, capture_output=True, text=True, timeout=timeout, check=False,
                )
            except subprocess.TimeoutExpired:
                return {
                    "mutant_id": mutant["id"],
                    "status": "timeout",
                    "killing_tests": [],
                    "wall_clock_seconds": timeout,
                    "cache_status": "miss",
                }
    except Exception as e:
        return {
            "mutant_id": mutant["id"],
            "status": "error",
            "killing_tests": [],
            "wall_clock_seconds": round(time.monotonic() - started, 2),
            "error": str(e),
            "cache_status": "miss",
        }

    elapsed = round(time.monotonic() - started, 2)
    output = proc.stdout + "\n" + proc.stderr
    failed = _FAIL_RE.findall(output)

    if proc.returncode == 0:
        return {
            "mutant_id": mutant["id"], "status": "survived",
            "killing_tests": [], "wall_clock_seconds": elapsed, "cache_status": "miss",
        }
    if failed:
        return {
            "mutant_id": mutant["id"], "status": "killed",
            "killing_tests": failed, "wall_clock_seconds": elapsed, "cache_status": "miss",
        }
    return {
        "mutant_id": mutant["id"], "status": "error",
        "killing_tests": [],
        "wall_clock_seconds": elapsed,
        "detail": output[-400:],
        "cache_status": "miss",
    }


_AD_HOC_TEMPLATE = textwrap.dedent("""
    # Auto-generated by adversarial runner.
    # case_id: {case_id}
    import importlib

    def test_adversarial_case():
        # Resolve SUT.
        module_path = {module_path!r}
        symbol = {symbol!r}
        mod = importlib.import_module(module_path)
        fn = mod
        for part in symbol.split('.'):
            fn = getattr(fn, part)

        # Construct input.
        observed = {invocation}

        # Compare against expected.
        expected_repr = {expected!r}
        # The adversarial generator emits Python literal `expected_value` in `expected_behavior`
        # when machine-checkable; otherwise this remains a soft check.
        assert repr(observed) == expected_repr or expected_repr == 'ANY', (
            f"adversarial mismatch: observed={{observed!r}} expected={{expected_repr}}"
        )
""")


def run_adversarial_case(case: dict) -> dict:
    """Render an ad-hoc test, run it, classify verdict.

    The case must include:
      target_symbol: e.g. "src/pricing.py:apply_discount" or "pricing:apply_discount"
      invocation:    a Python expression that calls SUT with the input
      expected:      a repr() string of the expected value, or 'ANY'
    """
    sym = case["target_symbol"]
    if ":" in sym:
        module_path, symbol = sym.split(":", 1)
        module_path = module_path.removesuffix(".py").replace("/", ".")
    else:
        module_path, symbol = sym.rsplit(".", 1) if "." in sym else (sym, "")

    rendered = _AD_HOC_TEMPLATE.format(
        case_id=case["case_id"],
        module_path=module_path,
        symbol=symbol,
        invocation=case.get("invocation", "fn()"),
        expected=case.get("expected", "ANY"),
    )

    with tempfile.NamedTemporaryFile("w", prefix="adv_", suffix=".py", delete=False) as f:
        f.write(rendered)
        ad_hoc_path = Path(f.name)

    try:
        started = time.monotonic()
        proc = subprocess.run(
            _PYTEST + ["-v", str(ad_hoc_path)],
            capture_output=True, text=True, timeout=case.get("timeout", 20), check=False,
        )
        elapsed = round(time.monotonic() - started, 2)
        passed = (proc.returncode == 0)
        # caught_by_existing_test is impossible here (this case is novel by
        # construction). The verdict is uncaught if the SUT failed our
        # expected check, caught_by_existing_test if the SUT matched, and
        # inconclusive if pytest errored before evaluation.
        if passed:
            verdict = "caught_by_existing_test"
        elif "AssertionError" in proc.stdout + proc.stderr:
            verdict = "uncaught"
        else:
            verdict = "inconclusive"
        return {
            "case_id": case["case_id"],
            "verdict": verdict,
            "observed_behavior": (proc.stdout + proc.stderr)[-400:],
            "wall_clock_seconds": elapsed,
        }
    finally:
        try:
            ad_hoc_path.unlink()
        except OSError:
            pass


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--mutant", help="mutant JSON path")
    g.add_argument("--case", help="adversarial case JSON path")
    ap.add_argument("--tests", nargs="*", default=[])
    ap.add_argument("--timeout", type=int, default=30)
    args = ap.parse_args()

    if args.mutant:
        m = json.loads(Path(args.mutant).read_text())
        print(json.dumps(run_tests_for_mutant(m, args.tests, args.timeout), indent=2))
    else:
        c = json.loads(Path(args.case).read_text())
        print(json.dumps(run_adversarial_case(c), indent=2))


if __name__ == "__main__":
    main()
